model_params:
  name: 'wae_mmd'
  in_channels: 1
  latent_dim: 128
  hidden_dims: [32, 64, 128]
  reg_weight: 1000
  kernel_type: 'rbf'
  hidden_multiplier: 9
  last_layer_size: [3, 3]

data_params:
  data_path: "../../data/mnist_data"
  mode: "image2audio"
  train_batch_size: 32
  val_batch_size: 32
  patch_size: 32
  num_workers: 8
  data_class: MNISTMultimodal

exp_params:
  LR: 0.00005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: "WaeMMD"
